### ISSUE TITLE
Sprememba characterja v data frame-u

### ISSUE THREAD

**Issue by dePauk** [dePauk/APPR-2018-19#1]
Pozdravljeni!

Rad bi spremenil dve imeni ekip v prvem stolpcu tabele. Spremeniti ju moram, da bom tabeli lahko združil v eno, vendar mi po popravku enega vektor nastavi na "atomic" in zamenjava drugega ni mogoča. Z "sub(...) %>% sub(...)" pa mi funkcija popravi le prvo.

Problem se nahaja v /uvoz/uvoz.r vrsticah od 113 naprej:

https://github.com/dePauk/APPR-2018-19/blob/48d4cedbbf9ea3efd6ebf8b7c9f4b5985479bce2/uvoz/uvoz.r#L113

**Comment by jaanos** [comment]
Najprej, funkcije `uvozi.igralce_tedna` nikjer ne kličeš, zato pride do napake, ko se prvič skličeš na spremenljivko `igralci_tedna`. Funkcijo bo treba dopolniti, da vrača celotno razpredelnico (dodaj še `return(igralci_tedna)` pred koncem funkcije - sicer se vrne samo nazadnje popravljen stolpec) in jo potem poklicati:
```R
igralci_tedna <- uvozi.igralce_tedna()
```
Podobno bo seveda treba narediti še z ostalimi funkcijami.

Notacija `x %>% f(a) %>% g(b)` je ekvivalentna `g(f(x, a), b)` - "vhod" v `%>%` se torej uporabi kot prvi argument sledeče funkcije. Pri `sub` tako ne bo šlo, saj gre vrednost, ki jo verižiš, v tretji argument. Lahko pa namesto funkcije podaš izraz v zavitih oklepajih - vhod je potem predstavljen s piko:
```R
tabela_stevilo_nazivov_imena <- as.character(tabela_stevilo_nazivov2$Var1) %>%
  { sub("New York Knicks", "New York Knickerbockers", ., fixed=TRUE) } %>%
  { sub("Philadelphia Sixers", "Philadelphia 76ers", ., fixed=TRUE) }
```

Lahko si pa pripraviš ustrezno funkcijo, ki jo bo lažje verižiti, npr.
```R
mysub <- function(x, pat, rep) sub(pat, rep, x, fixed=TRUE)
tabela_stevilo_nazivov_imena <- as.character(tabela_stevilo_nazivov2$Var1) %>%
  mysub("New York Knicks", "New York Knickerbockers") %>%
  mysub("Philadelphia Sixers", "Philadelphia 76ers")
```

V obeh primerih dobiš seveda samo vektor imen, ki ga lahko potem uporabiš v želeni razpredelnici, npr.
```R
stevilo_nazivov <- tabela_stevilo_nazivov2 %>%
  transmute(Ekipa=tabela_stevilo_nazivov_imena, Stevilo=Freq)
```

Mimogrede: v svoji kodi ne kliči funkcije `View`, saj nočeš, da bi se med prevajanjem poročila prikazovale razpredelnice. Dokler še delaš uvoz, je sicer koristno, da vidiš, kako razpredelnice izgledajo, kasneje pa te vrstice raje zakomentiraj ali izbriši.

**Comment by dePauk** [comment]
Najlepša hvala!
