### ISSUE TITLE
Sprememba grafa

### ISSUE THREAD

**Issue by dePauk** [dePauk/APPR-2018-19#3]
Pozdravljeni!

Pri grafu znotraj vizualizacija/vizualizacija.r v vrstici 45 imam zaenkrat določene barve glede na uspešnost ekip v rednem delu (iz tabele podatki.join), vsi stolpci (bars) imajo po defaultu vrednost count = 1.00

Graf bi rad preoblikoval tako, da bi bila višina stolpcev odvisna od vrednosti "Stevilo" iz tabele podatki.join, medtem ko bi barve ostale enake kot sedaj, torej v odvisnosti od spremenljivke "Uspesnost_redni_del" in potem vrstni red stolpcev določil glede na "Uspesnost_redni_del". Na prosojnicah iz predavanj je nekaj podobnega narejeno s funkcijo "factor", vendar mi vse skupaj ni povsem jasno.

**Comment by jaanos** [comment]
Da prikažeš stolpčni graf s številkami, ki jih imaš v razpredelnici, namesto `geom_bar()` uporabi `geom_col()` (prejšnja funkcija namreč prikaže pogostosti podanih vrednosti v podatkih), pri `aes` pa podaj še parameter `y` z imenom stolpca s številsko vrednostjo. Pri `aes` lahko sicer podajaš kar imena stolpcev - ker je razpredelnica že podata s parametrom `data`, bo `ggplot2` že vedel, na kaj se nanašajo:
```R
ggplot(data=podatki.join, aes(x=Kratice, y=Uspesnost_redni_del)) +
  geom_col() + xlab("Ekipa") 
```
Seveda poskrbi še za ustrezen izpis oznak na osi x ter oznake osi y.

Naj opozorim še, da razpredelnica `podatki_ekipe_imensko` ni v obliki *tidy data*. Svetujem, da jo razbiješ na več razpredelnic - v eni imaš lahko celoštevilske vrednosti (npr. število zmag/porazov/playoffov itd.), v drugi uspešnosti, zadnja pa naj samo povezuje ime ekipe s kratico (pri prejšnjih dveh ohrani samo enega od teh stolpcev). Za pretvorbo v obliko *tidy data* uporabi funkcijo `melt` iz knjižnice `reshape2`. Taka oblika ti bo prišla prav, če boš želel npr. na isti graf narisati podatke, ki jih imaš trenutno v različnih stolpcih.

Da se bosta razpredelnici `statistika` in `tabela_allstar` dejansko uvozili, bo treba funkcijo poklicati (trenutno se samo kopira funkcija), npr.
```R
statistika <- uvozi.sezonsko_stat()
```
Za razpredelnico `statistika` podobno kot zgoraj velja, da jo ustrezno razbiješ na več razpredelnic v obliki *tidy data*. Pri `tabela_allstar` bo treba ustrezno razbrati podatke iz stolpca `Sezone_allstar`, če jih boš seveda uporabil.

Opažam še, da pri `geom_smooth` uporabljaš parameter `model=lm`, vendar to ne deluje. Če želiš uporabiti linearni model (oz. ustrezen model, podan s formulo), podaj parameter `method="lm"`.
