### ISSUE TITLE
Graf v Shinyju

### ISSUE THREAD

**Issue by dePauk** [dePauk/APPR-2018-19#4]
V Shinyju bi rad predstavil graf, ki bi podatke vzemal iz tabele "igralci_tedna" z možnostjo izbire vrednosti spremenljivke "Pozicija". 

Imam narejen facet_grid na ta način v /vizualizacija.r pod imenom "graf_pozicije_cas", vendar ne vem, kako bi iz tega napisal kodo za shiny, ki bi prikazala le enega od pravokotnikov, odvisno od uporabnikove izbire.

Če se iz "graf_pozicije_cas" željenega novega grafa v Shinyju ne da predstaviti, bi ga naredil na novo iz tabele "igralci_tedna", kar sem sicer na koncu poizkušal, vendar ne vem kako naprej.

**Comment by jaanos** [comment]
V `server.R` izrišeš graf, pri čemer podatke ustrezno filtriraš glede na `input$id_poz` (ker je tako ime podano pri `selectInput`), npr.
```R
  output$graf1 <- renderPlot({
    ggplot(data=igralci_tedna_pozicijefilt %>% filter(Pozicija == input$id_poz),
           aes(x=Sezona_okrajsano)) + xlab("Leto") + ylab("Število") +
      geom_histogram(binwidth=1, color="gray30", fill="gray30") +
      theme_bw() + theme(axis.text.x = element_text(angle=90)) +
      ggtitle("Osvojeni nazivi igralca tedna glede na pozicijo igranja skozi čas")
  })
```
V `ui.R` potem graf izrišeš s `plotOutput("graf1")`. Svetujem še, da pri parametru `choices` pri `selectInput` uporabiš `unique` (npr. `choices=unique(igralci_tedna_pozicijefilt$Pozicija)`), da bo izbirnik bolje deloval.

Mimogrede, kot vidiš iz zgornjega primera, pri `aes` (pa tudi pri funkcijah iz knjižnice `dplyr`, kot npr. `filter`) ni potrebno navajati imena razpredelnice, če je bilo podano že pri `ggplot` - zadostuje že ime stolpca.

**Comment by dePauk** [comment]
Hvala!
